name: Deploy Documentation
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest'
          configfile: 'mkdocs.yml'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
            personal_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./site
            user_name: "github-actions[bot]"
            user_email: "github-actions[bot]@users.noreply.github.com"